include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    one_member_abstracts: ignore
    invalid_annotation_target: ignore
  exclude:
    - lib/**.*.dart

linter:
  rules:
    always_use_package_imports: true
    directives_ordering: true
    prefer_mixin: false
    public_member_api_docs: true
